---
#####################
## thesis metadata ##
#####################
title: The Psychology of Managerial Capital Allocation
author: Shir Dekel
college: Faculty of Science
university: The University of Sydney
university-logo: templates/usyd-logo.png
university-logo-width: 5cm
submitted-text: A thesis submitted to fulfil requirements for the degree of
degree: Doctor of Philosophy (Science)
degreedate: '`r format(Sys.time())`'
dedication: '\foreignlanguage{hebrew}{לאמא ואבא}'
originality: |
  `r paste(readLines("rmd/front_matter/originality.Rmd"), collapse = '\n  ')`
acknowledgements: |
  `r paste(readLines("rmd/front_matter/acknowledgements.Rmd"), collapse = '\n  ')`
preface: |
  `r paste(readLines("rmd/front_matter/preface.Rmd"), collapse = '\n  ')`
abstract: |
  `r paste(readLines("rmd/front_matter/abstract.Rmd"), collapse = '\n  ')`
abbreviations: |
  `r paste(readLines("rmd/front_matter/abbreviations.Rmd"), collapse = '\n  ')`

#######################
## bibliography path ##
#######################
bibliography: ["references.bib", "r-references.bib"]

########################
## PDF layout options ###
#########################

### abbreviations ###
abbreviations-width: 3.2cm
abbreviations-heading: List of Abbreviations

### citation and bibliography style ###
bibliography-heading-in-pdf: References

# biblatex options #
# unless you run into 'biber' error messages, use natbib as it lets you customise your bibliography directly
use-biblatex: true
bib-latex-options: "style=apa, backend=biber, refsegment=chapter"

### link highlighting ###
colored-not-bordered-links: true # true = highlight text of links - false = highlight links with border

# Set the link text/bord coloring here, in RGB. 
# Comment out a variable to just use whatever the text's existing color is. 
# If you wish NOT to highlight links, set colored-not-bordered-links: true, 
# and comment out the colors below
# "45,48,145" is equivalent to `Blue` from `dvipsnames`
urlcolor-rgb: "45,48,145"
citecolor-rgb: "45,48,145"
linkcolor-rgb: "45,48,145"

## binding / margins ##
page-layout: nobind #'nobind' for equal margins (PDF output), 'twoside' for two-sided binding (mirror margins and blank pages), leave blank for one-sided binding (left margin > right margin)

## position of page numbers ##
ordinary-page-number-foot-or-head: foot #'foot' puts page number in footer, 'head' in header
ordinary-page-number-position: C  #C = center, R = right, L = left. If page layout is 'twoside', O = odd pages and E = even pages. E.g. RO,LE puts the page number to the right on odd pages and left on even pages
chapter-page-number-foot-or-head: foot #you may want it to be different on the chapter pages
chapter-page-number-position: C

## position of running header ##
running-header: true #indicate current chapter/section in header?
running-header-foot-or-head: head
running-header-position-leftmark: LO #marks the chapter. If layout is 'nobind', only this is used.
running-header-position-rightmark: RE  #marks the section.

## section numbering ##
section-numbering-depth: 4 # to which depth should headings be numbered?

## tables of content ##
toc-depth: 2 # to which depth should headings be included in table of contents?
lof: true # include list of figures in front matter?
lot: true # include list of tables in front matter?
mini-toc: true  # include mini-table of contents at start of each chapter? (this just prepares it; you must also add \minitoc after the chapter titles)
mini-lot: false  # include mini-list of tables by start of each chapter?
mini-lof: false  # include mini-list of figures by start of each chapter?

## linespacing ##
linespacing: 22pt plus2pt # 22pt is official for submission & library copies
frontmatter-linespacing: 17pt plus1pt minus1pt #spacing in roman-numbered pages (acknowledgments, table of contents, etc.)

includeline-num: true #show line numbering in PDF?

# For lua filters to work
citeproc: no

documentclass: book
always_allow_html: true #this allows html stuff in word (.docx) output
# Needed for non-biblatex output (Word and HTML)
link-citations: true
csl: templates/apa.csl
---

```{r setup, include=FALSE}
library(magrittr)
library(magick)
library(here)
library(knitr)
library(papaja)
library(kableExtra)
library(targets)

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)

hook_chunk <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  txt <- hook_chunk(x, options)
  # add chunk option 'quote_author' which adds \qauthor{...} to the end of a chunk.
  # This is used to give the author of the cute quotes you can add to chapter openings
  if (!is.null(options$quote_author)) {
    latex_include <- paste0("\\\\qauthor\\{", options$quote_author, "\\}\\1")
    gsub("(\\\\end\\{savequote\\})", latex_include, txt)
  } else {
    return(txt) # pass to default hook
  }
})

## Automatically apply `printnum()` to any number that is printed in inline code
## chunks as in `papaja`
knitr::knit_hooks$set(inline = papaja:::inline_numbers)
```

```{r ebook-welcome, child = 'rmd/front_matter/welcome.Rmd', eval=knitr::is_html_output()}
```
