library(conflicted)
library(targets)
library(tarchetypes)
library(magrittr)
library(dplyr)
library(rlang)
library(tibble)
library(stringr)
library(ggplot2)
library(papaja)
library(afex)
library(purrr)
library(emmeans)
library(printy)
library(broom)
library(tidyr)
library(pwr)
library(forcats)
library(MOTE)
library(broom.mixed)
library(patchwork)
library(janitor)
library(snakecase)
library(yaml)
library(rmdfiltr)
library(knitr)
library(bookdown)
library(rmdfiltr)
library(magick)
library(cowplot)
library(ggbeeswarm)
library(scales)

## Custom thesis packages
library(shiR)
library(shirthesis)
library(aggregation1)
library(aggregation2)
library(aggregation3)
library(aggregation4)
library(alignment1)
library(alignment2)
library(alignment3)
library(alignment4)
library(alignment5)
library(alignment6)
library(alignment7)
library(alignment8)
library(anecdotes1)
library(anecdotes2)

conflict_prefer("filter", "dplyr")
conflict_prefer("set_names", "rlang")
conflict_prefer("discard", "purrr")
