### Discussion

Experiment 3 found some evidence for the effect of similarity on project choice,
but it was in the opposite direction to the one hypothesised. Specifically, the
results showed that when considering projects individually, participants' risk
aversion did not differ between similarity conditions, but when offered a
portfolio of the projects, those that saw the dissimilar projects were more
likely to invest.

These results provide evidence for the naive diversification account expressed
above (see Section \@ref(similarity-discussion-aggregation-1)). Specifically,
participants may really be naively diversifying, but only when they are
explicitly given an opportunity to do so. This is similar to the multi-play
effects because the question itself provides a sort of choice bracketing. That
is, the gambles are grouped together as a portfolio by the question. Together,
this suggests that people are not naively aggregating when viewing gambles in
isolation, but when the choices are bracketed explicitly, then the choice seems
to be driven by a naive diversification.
