### Discussion

Hypotheses \@ref(hyp:three-way-alignment-2), \@ref(hyp:allocation-alignment-alignment-2), \@ref(hyp:allocation-alignment-reliability-npv-alignment-2),
and \@ref(hyp:allocation-alignment-high-alignment-2) were supported in the
verbal reliability condition. This shows that, while overall participants
preferred to use NPV as a proxy for project quality in their allocations, they
still used verbal reliability information. Specifically, when projects were
similar, participants used NPV when they were told that it was reliable, and
used alternative metrics when told that it was not reliable. However, in
Experiment 3, no support was found for
Hypothesis \@ref(hyp:allocation-alignment-low-alignment-2). It was expected that
participants in the low alignment condition would use NPV regardless of the
reliability level conditions, as in Experiment 1. Rather, they used NPV less
when told that it was unreliable. However, they primarily used NPV overall, as
shown by the positive NPV trend in both reliability level conditions.

Further, Experiment 3 did not find evidence to support
Hypothesis \@ref(hyp:four-way-alignment-8), most likely because of the
unexpected effects of NPV in the numerical reliability condition. The hypothesis
was constructed in response to the results of a pilot study (documented in
Appendix \@ref(alignment-7)), which replicated the results of Experiment 1 in
the verbal reliability condition, but did not replicate the results of
Experiment 2 in the numerical reliability condition. That is, when faced with
numerical ranges as the NPV reliability information, participants did not even
use the midpoint in their decisions. On the contrary, Experiment 3 replicated
the finding of Experiment 2 for the numerical reliability condition.
Specifically, participants relied more on NPV when projects were dissimilar but,
critically, did not use numerical range information to influence their
allocations.

