## Experiment 4 {#alignment-1}

```{r setup-alignment-1}
tar_load(descriptives_alignment_1)
tar_load(materials_alignment_1)
tar_load(results_alignment_1)
tar_load(plot_alignment_1)
```

Experiment 4 further investigated the effects of alignment and verbal NPV
reliability information on capital allocation decisions. Experiment 4 used the
same methodology as in Experiment 1 (see Section \@ref(method-alignment-2)),
except for two main changes. First, the alignment conditions were manipulated
within subjects. Second, the no NPV condition in the NPV reliability variable
was removed.

The results of Experiment 1 were expected to replicate (see
Section \@ref(results-alignment-2)). Specifically, it was expected that in the
high alignment condition, participants will be able to respond to each
reliability condition, whereas, in the low alignment condition, they will rely
more on NPV regardless of reliability condition.

In addition to the all-project allocation data analysed above, analyses for just
the "target project" are also reported. This refers to allocation of capital to
the project that had the highest NPV, but the lowest value on concrete measures
intrinsic to the actual product (e.g., the capacity of a laptop in gigabytes).
Therefore, a higher allocation value indicated a higher reliance on NPV.
Further, the method and analyses for the confidence measure are also reported.

```{hypothesis, confidence-alignment-alignment-1, echo = TRUE}
Participants will be more confident about their decisions in the high alignment
condition than in the low alignment condition.
```
