### Results {#results-anecdotes-2-appendix}

#### Allocation

##### Similarity Manipulation Check

The similarity manipulation worked as expected, with the negative anecdote only
low similarity condition being allocated significantly more than those in the
high similarity condition,
`r results_anecdotes_2$allocation$anecdotes_only_similarity$valence_negative`. For positive
anecdotes, participants allocated more to the high similarity condition than
those in the low similarity condition,
`r results_anecdotes_2$allocation$anecdotes_only_similarity$valence_positive`

#### Ratings

##### Similarity Manipulation Check

Evidence for the similarity manipulation working was also seen in the rating
data. Participants rated anecdotes in the high similarity condition as more
similar to the target than those in the low similarity condition,
`r results_anecdotes_2$follow_up$similarity_rating_similarity`.

(ref:plot-anecdotes-2-similarity-rating) Mean similarity rating of Project A (the target project) to the anecdote. Error bars represent 95% confidence intervals.

```{r plot-anecdotes-2-similarity-rating, fig.cap = "(ref:plot-anecdotes-2-similarity-rating)"}
plot_anecdotes_2$similarity
```

##### Allocation is Influenced by Perceived Similarity

As hypothesised, allocation was influenced by perceived similarity. That is, in
the negative valence condition, there was a negative correlation between
allocation and similarity rating,
`r results_anecdotes_2$follow_up$allocation_similarity_rating$negative_high_low`.
However, in the positive valence condition,
there was a positive correlation between allocation and similarity rating,
`r results_anecdotes_2$follow_up$allocation_similarity_rating$positive_high_low`.

##### The Relationship Between Allocation and Specific-Relevance Depends on Similarity

In the negative valence condition, there was no significant difference between
the slopes of the high and low similarity conditions,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$high_low_negative`.
In the low similarity condition, allocation and specific-relevance rating were
not correlated,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$negative_loweffect`,
as in the low similarity condition,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$negative_higheffect`.

In the positive valence condition, there was no significant difference between
the slopes of the high and low similarity conditions,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$high_low_positive`.
In the low similarity condition, allocation and specific-relevance rating were
not correlated,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$positive_loweffect`,
as in the low similarity condition,
`r results_anecdotes_2$follow_up$allocation_specific_relevance$positive_higheffect`.

##### People do not Consider General-Relevance in Their Allocation

There were no significant correlations between allocation and general-relevance
rating.



