## Experiment 1 {#anecdotes-1}

```{r setup-anecdotes-1}
tar_load(descriptives_anecdotes_1)
tar_load(materials_anecdotes_1)
tar_load(results_anecdotes_1)
tar_load(plot_anecdotes_1)
```

Experiment 1 investigated the effects of anecdote similarity and bias on
capital allocation. Participants were assigned to the same conditions as those
in @wainberg2018 except that an anecdote only condition was included and the
judgement orientation I condition was excluded. They were then asked to allocate
a hypothetical budget between two business projects. Participants were also
presented with a case study that was either similar or dissimilar to the target
project (but still from the same industry). Further, for the conditions in which
statistical evidence was provided, participants were presented with aggregated
information about the success of similar projects in the form of NPV as well as
a reliability measure. One project was clearly better than the other in terms of
the statistical data, but the anecdotal evidence suggested the opposite.

Previous research has found that people are persuaded more by negative anecdotes
than by positive statistical data in capital allocation scenarios
[@wainberg2018]. While studies have shown that similar anecdotes are more
persuasive than dissimilar anecdotes [@hoeken2009\; Study 3], it is unclear how
the anecdotal bias effect may depend on anecdote similarity. Thus, the main
question is whether anecdotal bias will be greater when the anecdote is similar
to the target project compared with when it is dissimilar. The target project
was supported by the statistics but was inconsistent with the anecdotes.
Further, Experiment 1 only used negative anecdotes. Therefore, the experiment
would show evidence of anecdotal bias if participants assigned to the statistics
only condition allocated more money to the target project compared with those in
the anecdote & statistics condition. Therefore, Experiment 1 tested the
following hypothesis:

```{hypothesis, anecdote-similarity-anecdotes-1, name = "anecdotal bias depends on the similarity of negative anecdotes", echo = TRUE}
Budget allocations to the target project will be higher when statistics only are
presented compared with when statistics are accompanied by an anecdote with high
similarity to the target project. In addition, budget allocations will not be
affected by anecdotes with low similarity. That is, the statistics only
condition will not differ from the low-similarity anecdote & statistics
condition.
```

Experiment 1 predicted that that the anecdotal bias effect will be complete, as
in @wainberg2013. Specifically, the participants presented with the
high-similarity anecdote along with the statistics would not use any statistical
information. Testing the high similarity condition will provide an equivalent
test to that of @wainberg2013. Therefore, Experiment 1 tested the following:

```{hypothesis, statistics-anecdotes-1, name = "effect of statistics for negative anecdotes", echo = TRUE}
Participants in the high-similarity anecdote & statistics condition (without the
enhanced statistics explanation) and those in the high-similarity anecdote only
condition will allocate capital equally to the target project.
```

Participants with additional information on the importance of scientific
thinking and statistical data may be less affected by anecdotes. @wainberg2018
termed this the *judgement orientation II* condition, while in this experiment
it is termed the *anecdote & enhanced statistics condition*. Unlike the anecdote
& enhanced statistics condition in @wainberg2013, the statistical information
here is actually "enhanced" because of the accompanying text. Experiment 1
tested whether the effect of additional information on anecdotal bias would be
replicated in a capital allocation scenario. Therefore, Experiment 1 tested the
following hypothesis:

```{hypothesis, enhanced-statistics-anecdotes-1, name = "effect of enhanced statistics for negative anecdotes", echo = TRUE}
Participants in the high-similarity anecdote & enhanced statistics condition
will allocate more capital to the target project than those in the
high-similarity anecdote & statistics condition.
```


