## Experiment 2 {#anecdotes-2}

```{r setup-anecdotes-2}
tar_load(descriptives_anecdotes_2)
tar_load(materials_anecdotes_2)
tar_load(results_anecdotes_2)
tar_load(plot_anecdotes_2)
```

Experiment 1 replicated the anecdotal bias effect found in the literature. That
is, participants allocated less capital to a project when presented with an
anecdote & conflicting statistics compared with when they were presented with
the statistics only. However, this effect depended on anecdote similarity, such
that anecdotal bias was stronger when the anecdote was similar to the current
task compared with when it was dissimilar. a negative anecdote only was used
Experiment 1 because previous research has found anecdotal bias for negative but
not for positive anecdotes [@jaramillo2019]. However, @jaramillo2019
investigated medical decision-making, and the effect of anecdote valence may be
different in a business context. In the study by @jaramillo2019, the positive
anecdote involved a treatment that led to a reduction in symptoms, while the
negative anecdote involved symptoms persisting. This framing may have led
participants to perceive the positive anecdote as a return to a reference point
and the negative anecdote as a continuation of a reduction in wellbeing relative
to the reference point. In business, however, both successful and failed
business projects represent a deviation from a reference point. To test this
difference further, manipulation of anecdote valence was added to Experiment 2.

To increase the experiment's power, anecdote valence and anecdote similarity
were manipulated within subjects. Further, Experiment 2 did not include the
anecdote & enhanced statistics condition because Experiment 1 found no
evidence for its effect. All participants saw the statistics only condition,
which did not contain an anecdote; therefore, this did not need to be
manipulated between subjects. Therefore, each participant was shown five
displays: one for the statistics only condition, and four for either the
anecdote only condition or the anecdote & statistics condition. These four
anecdote displays consisted of the similarity (low and high) $\times$ valence
(negative and positive) conditions.

In Experiment 1, assumptions about the pool from which the anecdote was sampled
were not clarified. In Experiment 2, participants were told that the anecdote
was sampled randomly and that it was not uniquely similar to the target project.
This was expected to lead to a reliance on statistical evidence, regardless of
the anecdote's similarity. However, people often struggle to use statistical
concepts presented descriptively, as seen in the enhanced statistics condition
in Experiment 1, the neglect of variance shown in Chapter \@ref(alignment), and
the lack of risk aggregation in descriptive risky decisions shown in
Chapter \@ref(aggregation). Therefore, it was expected that the results of
Experiment 1 would be replicated for the negative valence condition. Further, it
was expected that there would be a reverse effect in the positive valence
condition. Appendix \@ref(anecdotes-2-appendix) shows a simulation of the
hypothesised effects. Therefore, Experiment 2 tested the following hypothesis:

```{hypothesis, three-way-anecdotes-2, name = "overall effect", echo = TRUE}
The three-way similarity $\times$ valence $\times$ anecdote (excluding
statistics only) interaction is significant
```

The main effect of interest was the effect of anecdote similarity on anecdotal
bias. Therefore, as well as retesting
Hypothesis \@ref(hyp:anecdote-similarity-anecdotes-1) for negative anecdotes,
Experiment 2 tested the following hypothesis:

```{hypothesis, anecdote-similarity-anecdotes-2, name = "anecdotal bias depends on the similarity of positive anecdotes", echo = TRUE}
For positive anecdotes, budget allocations to the target project will be higher
in the statistics only condition than in both the anecdote & statistics
conditions (high and low similarity). Within these two anecdote & statistics
conditions, allocations will be higher when the anecdote is similar to the
target project compared with when it is dissimilar.
```

Contrary to both @wainberg2013 and Hypothesis \@ref(hyp:statistics-anecdotes-1),
Experiment 1 found that participants do integrate statistics in their decisions
to some extent. This effect was expected to be replicated in Experiment 2.
Therefore, Experiment 2 tested the following hypotheses:

```{hypothesis, statistics-negative-anecdotes-2, name = "effect of statistics for negative anecdotes", echo = TRUE}
For negative anecdotes, budget allocations to the target project will be higher
for the high-similarity anecdote & statistics condition than for the
high-similarity anecdote only condition.
```

```{hypothesis, statistics-positive-anecdotes-2, name = "effect of statistics for positive anecdotes", echo = TRUE}
For positive anecdotes, budget allocations to the target project will be higher
for the high-similarity anecdote only condition than for the high-similarity
statistics & anecdote condition.
```

