## Experiment 4 {#aggregation-4}

```{r setup-aggregation-4}
tar_load(descriptives_aggregation_4)
tar_load(materials_aggregation_4)
tar_load(results_aggregation_4)
tar_load(plot_aggregation_4)
```

Experiment 4 investigated the effect of awareness on project choice.
Experiment 1 found an effect of awareness in the trial-by-trial data that was
not replicated in Experiment 2. Above, this effect was explained through the law
of small numbers: people may have been anticipating less risky gambles towards
the end of the set. As such, the effect could be seen with more trials.
Experiment 4 attempted to replicate the effect from Experiment 1 with 20
projects. The *naive* condition attempted to encourage participants to focus on
projects one at a time and did not reveal the total number of projects. The
*aware* condition attempted to encourage participants to think of all 20
projects. This was done by revealing the total number of projects in the
beginning of the task and by identifying at each project display its order in
the sequence. Experiment 4 again tested
Hypothesis \@ref(hyp:awareness-trials-aggregation-2).
