## Capital Allocation in Hierarchical Organisations {#capital-allocation}

<!-- Large organisations have hierarchies -->

The purpose of a multi-divisional organisation is to generate more value than
any of the individual divisions combined. The whole should be greater than the
sum of its parts. Previous work suggests that this is achieved due to factors
such as reduced transaction costs [@williamson1981; @teece1982; @teece1980;
@coase1937; @liebeskind2000], shared resources [@wernerfelt1984; @barney1991],
increased competitive advantage [@porter1980; @porter1985], increased monitoring
[@gertner1994], and increased synergies [@barney1988]. The underlying logic is
the same: a multi-divisional organisation will be successful if it manages its
divisions using processes and resources that are shared or, better yet, are
complementary.

<!-- Managers evaluate projects to potentially invest in -->

In order to successfully manage multiple units, large organisations developed a
hierarchical structure. @bower1970 identified three levels of the typical
management hierarchy: business, division, and corporate. These are equivalent to
front-line (or bottom), middle, and top level managers [@noda1996]. Early
theorists suggested that the strategy for the organisation's growth is driven
completely by the top managers; the rest of the organisation simply enacts their
proposals. However, @mintzberg1985 emphasised the role of an emergent strategy,
in which lower level managers affect change in the organisation's strategy.
Other work proposed and found evidence for an iterated process in which a
strategic context may be set by top managers, but business projects advanced by
lower level managers also contribute to driving the strategy of the organisation
[@noda1996; @burgelman1983; @bower1970].

The way that capital is allocated in an organisation is very important to its
growth and longevity. This process is a part of the broader process of resource
allocation. A *resource* can refer to many types of assets that an organisation
owns, both tangible and intangible, of which capital is only one
[@wernerfelt1984]. The capital allocation process itself is an important driver
of the strategic outcomes of an organisation [@bower1970; @bower2005], and as a
result, is an important influence on its financial performance [e.g.,
@arrfelt2015; @bardolet2010]. @sengul2019 [p. 72] describe intra-firm capital
allocation as "(i) a process of determination, comparison, and selection among
multiple investment alternatives, (ii) taking place across organizational levels
of the firm, and (iii) influenced and constrained by the external context in
which the firm is situated." In capital allocation, business-level managers
typically formulate project proposals, which their division managers then
evaluate. The division managers then choose the projects to send for final
approval with the corporate managers. The supply of available capital is also
influenced by external sources such as investors, competitors, and customers.
However, this thesis focuses on the comparison and selection processes that are
relevant during business project evaluation.

<!-- They have limited information -->

Managers ultimately have only limited information about the projects that they
evaluate. They typically have access to descriptive information about the
investment and its known properties, but also are provided with financial
metrics that estimate the returns on the investment. There are many such
metrics; they usually attempt to encapsulate a trade-off between predicted
future gains, present losses (in the form of the capital spent to pay for the
investment), and opportunity costs. Examples include net present value (NPV),
internal rate of return, return on investment, cost-benefit, and pay-back
period. This thesis focuses on NPV, since it is one of the most frequently used
metrics for project evaluation [@graham2001; @remer1993; @graham2015]. NPV is
the difference between the money that a project is forecasted to make and the
initial investment in its development (accounting for the time value of money),
as shown in Equation \@ref(eq:npv):

\begin{equation}
\text{NPV}=\sum_{t=0}^n \frac{R_t}{(1+i)^t}, (\#eq:npv)
\end{equation}

where $t$ is the time of the cash flow, $i$ is the discount rate, $R_t$ is the
net cash flow, and $n$ is the total number of periods. NPV is a useful metric
because simply knowing that it is positive suggests that the project that it
describes should be profitable. Therefore, metrics such as these have a strong
influence on the decision of the manager evaluating a project.

<!-- Influences on the decision -->

However, there are other influences on project evaluations other than the value
of the financial metrics. For instance, politics within or outside the company
can lead to situations in which a decision is based on social influence or even
manipulation [@garbuio2017]. Such influence is not necessarily negative; it may
involve qualitative feedback from, for instance, a more senior manager
[@thamhain2014]. Research has also shown that the media can have a tangible
influence on managerial decision-making [@bednar2013; @liu2013]. Other sources
of influence are the organisational structures and incentives that are in place
both externally [@kokkinis2019] and internally to the organisation
[@ullrich2004; @rajan2000]. Such dynamics have also been the subject of economic
modelling investigations [@reichelstein1997; @cavagnac2005; @ortner2017].
Project proposals might also be affected by certain approval structures. For
instance, managers might submit overly-optimistic project proposals if they know
that the corporate team only accepts projects with a certain minimum NPV
forecast.

Another potential organisational influence on capital allocation is the extent
of diversification present in an organisation. A diversified organisation is one
that possesses different divisions that are unrelated in some way. @penrose2009
[p. 96] defined it as such:

> a firm diversifies its productive activities whenever, without entirely
> abandoning its old lines of product, it embarks upon the production of new
> products, including intermediate products, which are sufficiently different
> from the other products it produces to imply some significant difference in
> the firm’s production or distribution programmes.

Previous work found that organisations that are made up of more related
divisions are more successful than those that are made up of unrelated divisions
[@harrison1993; @rumelt1974; @shelton1988; @wernerfelt1988]. This is also true
within business divisions [@davis1992]. However, *more* diversified firms have
also been shown to be associated with profitability [@grant1988]. This is
usually explained by the ability for such firms to avoid risk associated with
any one market. Some of the discrepancy in diversification findings has been
explained to be due to the specific measures used [@lubatkin1986]. It may also
be because most studies used Standard Industrial Classification (SIC) codes to
measure diversification [e.g., @rumelt1974], whereas others operationalised it
using other approaches [e.g., resource-based\; @harrison1993].

The advantage that related organisations have had has been explained through
*synergies* [@barney1988]. That is, an organisation with two divisions that can
use their resources to better one another are better off together than
separately. The 1960s saw a general rise in mergers and acquisitions from
executives seeking to diversify their organisations. However, doing so simply
for the sake of increasing divisions, rather than an understanding of the
possible synergies, leads to the organisation actually being worth less than the
sum of its parts [known as a *diversification discount*\; @lang1994]. In fact,
many organisations that acquired other businesses to diversify subsequently end
up divesting them [@porter1987]. For instance, in 2018 Australian conglomerate
Wesfarmers demerged its Coles division, a successful retailer. Since then, the
share price for both companies has risen by approximately 62% and 32%,
respectively [@boyd2021].

While much of the performance of an organisation depends on influences that are
external to the individual managers (e.g., organisational, political),
psychological factors are often also quite consequential. For instance, on the
one hand, organisational factors such as relevant support teams and approval
processes may influence capital allocation depending on the extent of an
organisation's extent of diversification. On the other hand, psychological
factors such as ability of managers to compare between business project
proposals may also impact allocation differently depending on the organisation's
diversification. It is likely to be more difficult for a manager to evaluate
project proposals from two dissimilar divisions that it is to evaluate those
from two similar divisions. The organisational influences discussed above often
assume that the manager that is making the decisions acts rationally, as per
traditional economic theory. However, surveys of executives show that CEOs and
CFOs often rely on non-financial factors for capital allocation decisions
[@graham2015]. Executives in these surveys identified manager reputation and
confidence as two of the most important factors for capital allocation
decisions. Further, research in psychology has shown that cognitive biases can
influence such capital allocation decisions. Section \@ref(psychology) discusses
such biases and the relevant implications for the thesis.
