(ref:introduction-quote) ---Elbert @hubbard1914 [p. 52]

```{block type='savequote', quote_author='(ref:introduction-quote)', include=knitr::is_latex_output(), echo = TRUE}
Executive: A man who can make quick decisions and is sometimes right.
```

# Introduction {#introduction}

\minitoc

<!-- Organisations have a big impact on the world -->

Much of modern life depends on large organisations. General Electric (GE) makes
the engines that power our aircrafts, Johnson & Johnson makes our shampoo, and
Google allows us to search the internet. The areas of our lives that are less
affected by such private firms depend on public sector organisations such as
public hospitals, schools, and police. The justification for the existence of
organisations of this size is that the particular combination of individual
divisions, alongside a corporate management, will lead to better performance for
each of the divisions than they would have been able to generate individually.
In other words, the assumption is that such organisations create a synergy---the
quality of the whole will be greater than the sum of its parts.

<!-- They are made up of multiple divisions -->

Multi-divisional organisations are typically organised in a hierarchical
structure, with a corporate management team and subsidiary divisions. Each
division can be made up of several business units. For instance, some of GE's
divisions include GE Aviation and GE Healthcare. Similarly, in the public
sector, a hospital system may operate through multiple individual hospitals in
different regions.

<!-- This means capital allocation -->

Such organisations therefore need to make capital allocation decisions. That is,
given a limited amount of financial resources, how best to invest in the
multiple divisions? Equally? Pick a winner? What metric should be used to
compare across divisions? Capital allocation is a critical process to the
operation and development of multi-divisional organisations.

<!-- Many decisions come from one or few people -->

The products and services that arise from organisations are necessarily a result
of the work of many people. In GE, for instance, the factories that generate
aircraft engines need to be staffed by production line workers, accountants are
needed for bookkeeping, and software engineers are needed to design and maintain
the production systems. Despite this, many important strategic decisions
ultimately come from a very small number of people. The decisions that the CEO
or other lower level executives make can have large consequences on the life of
the company.

<!-- Managers are biased -->

It is often assumed that a few people having a lot of decision-making power is
for the best. Managers of large organisations often appear to be bold and
effective decision-makers. It appears that their position of power and wealth
was necessarily arrived at through high competence and rational decision-making,
suggesting that the organisation is in good hands. However, there are three
reasons why it may be concerning that much of an organisation's future---and by
extension often many more components of the economy---depends on the decisions
of a few individual. First, the role of survivorship bias in obtaining the
manager's role is unclear, because the number of managers that used the same
management strategy and failed is unknown. Second, decades of work have shown
that people's decision-making is often fallible and that job experience does not
always alleviate this fallibility. Third, managers of large organisations often
face uncertain environments, which increases the likelihood of managers facing
psychological biases.

There are many examples of companies that suffered due to such biases.
Overconfidence and confirmation bias likely played a part in Blockbuster's
famous refusal of an offer to buy Netflix in 2000 [@meissner2015]. @roxburgh2003
identified how Equitable Life Assurance Society unnecessarily anchored on
previous interest rate performance and was unprepared when rates changed. In an
example of the sunk-cost fallacy, the London Stock Exchange continued investing
in an automated-settlement system even when it no longer remained profitable.
The Bank of England needed to step in and stop the project. Overconfidence in
market entry is also a common issue, illustrated by EMI's introduction into the
medical-diagnostics market with the CT scanner [@horn2005; @camerer1999]. By
underestimating the competition and overestimating their own capabilities they
eventually incurred losses and exited the market.

<!-- Not enough work on capital allocation biases -->

One class of biases has not been well studied: capital allocation biases. While
some previous work investigating these biases exists [e.g., @bardolet2011], many
questions still remain unanswered. This is a rather large hole in the literature
because capital allocation decisions are at the centre of executive and lower
level managers’ roles. When making capital allocation decisions, there are
elements of the decision-making environment that can be deceiving for managers.
This thesis examines how the framing of a series of business projects affects
people's decisions about those projects. Specifically, the same set of projects,
presented in aggregate form, is much more likely to be accepted. Further,
sometimes people are distracted by extraneous semantic information, such as the
relative similarity of the options.

The results of the thesis show that although people in general make sensible
decisions, they fail to moderate them appropriately when presented with critical
information. Specifically, information about metric variance is ignored even
when other metrics are available. Further, people seem to appropriately use
statistical and anecdotal information based on relevance to the situation at
hand, but ignore information about the sampling of the anecdote. Not
appropriately using these kinds of statistical concepts has important
financial consequences, discussed below.

All the experiments in the thesis use laypeople, except for one experiment.
However, past work generally shows the same biases in managers and laypeople
[with some showing more bias in managers, e.g., @haigh2005]. Further, upcoming
studies will directly test managers to determine any potential expertise
effects.

Section \@ref(capital-allocation) will explain how the capital allocation
process functions in hierarchical organisations and why it is necessary to
analyse such a process with a psychological approach. Section \@ref(psychology)
reviews the literature on decision-making biases and how these may apply to
capital allocation decisions. Section \@ref(chapter-overview) will then
summarise the rest of the thesis chapters.
