## The psychology of resource allocation {#psychology}

Managers of large organisations are generally assumed to have a superior
decision-making capability to non-managers. However, managerial decision-making
involves many of the same processes that have been shown to be affected by
psychological biases in the general population [@schwenk1984; @das1999;
@mccray2002]. Further, an organisation's success ultimately depends on
"strategic" decisions made by top level managers [@mazzolini1981]. Therefore,
despite early work attempting to analyse such decisions using a structured
organisational analysis [e.g., @mintzberg1976], it is important to understand
the potential influence of psychological biases on managerial decisions.

Psychological research has shown that people tend to make decisions that are
inconsistent with neoclassical economic theory. For instance, Expected Utility
Theory [EUT\; @friedman1948; @vonneumann1944] assumed that people have complete
information when making decisions. However, both laypeople and managers of
organisations are limited in the amount of information that they have and their
ability to use it [@simon1955; @cyert1956]. Such inconsistencies with economic
prescription are likely to have evolutionary origins, so are sure to be adaptive
in certain environments [@haselton2009; @gigerenzer2008]. However, there are
many situations in which such inconsistency with economic theory can have bad
consequences.

<!-- Previous research  -->

Research has shown many ways in which the allocation of resources in an
organisation can be influenced by psychological biases. For instance,
@benartzi2001 found that people tend to allocate their retirement fund equally
between the available options, regardless of their composition. This bias was
also found in capital allocation for hierarchical firms [@bardolet2011].
Managers allocate resources equally across the available divisions in the firm,
regardless of performance. This behaviour may be damaging to firm performance
because it means that lower performing business units may be getting subsidised
by higher performing units, which are not operating at their full potential.

Relatedly, people tend to continue expending resources into investments that
appear to be failing [@staw1981]. This *escalating commitment* is another way
that psychological biases can influence allocation in an organisation. This
pattern of decision-making is likely a consequence of the sunk cost fallacy, in
which people avoid "cutting their losses" even when they know that they cannot
recuperate an investment [@parayre1995].

The way that information is presented can often influence allocations. For
instance, @yates1978 showed that people's evaluations are sensitive to the level
of detail in the information provided. They found that people devalued
descriptions of university courses more when they had less detail. This may be
relevant for managers evaluating project proposals. A proposal might appear more
attractive simply due to the level of detail in it, even if the level of detail
does not correspond with the quality of each proposal.

Further, people tend to be over-confident in their decisions and forecasts
[@langer1975; @mannes2013; @soll2004; @puri2007], as do IT professionals
[@mckenzie2008] and managers [@lovallo2003; @kahneman1993; @baroneadesi2013].
This is important for higher-level managers that evaluate project proposals,
both because the metrics that rely on estimates may be biased by the
over-confidence of the lower-level manager that created the proposal and because
the higher-level manager may in turn be over-confident about the prospects of
the proposal due to factors that are unrelated to the underlying value.
Overconfidence is also seen when considering the success of projects in
hindsight [@bukszar1988; @christensenszalanski1991]. This means that it less
likely that managers will be able to effectively learn from both past mistakes
and successes due to the potentially erroneous belief that the outcome was
anticipated.

Managers often create sensitivity analyses, estimating the worst case, best
case, and most likely scenario for a forecast. However, these are likely to be
anchored on past experiences that further the manager's existing beliefs. In
fact, prior research has shown that people are poor at constructing subjective
probability distributions [e.g., @alpert1982; @schaefer1973;
@staelvonholstein1971; @tversky1974]. Therefore, this suggests that even if the
lower-level managers that construct project proposals calibrate their forecasts
so that they are not over-confident, they are still likely to provide inaccurate
estimates of their degree of confidence.

The above summarises many of the currently known psychological biases related to
resource allocation. This thesis focuses on three essential processes within the
resource allocation process. When evaluating projects in hierarchical
organisations, there is often 1. an element of risky choice, 2. a comparison
between diversified businesses, and 3. a comparison between the target project
and prior experience. Each of these is prone to separate biases, that are also
interrelated. I review the literature for these processes in the subsequent
subsections.

### Risky choice

<!-- Utility -->

Neoclassical theories such as EUT suggest that when faced with multiple risky
options people should choose the option with the highest Expected Value (EV),
all else being equal. This means multiplying the value of each option by its
probability and comparing the resulting values [first documented in
@pascal1999]. For instance, imagine being presented with the following two
choices:

A) a gamble that involves a 50% chance gaining $200 and a 50% chance of losing
$100; or
B) gaining/losing nothing.

In option A, the EV is calculated as $200 \cdot 0.5 - 100 \cdot 0.5 = 50$. Since
the EV for option A (50) is higher than the EV for option B (0), EUT would
suggest that option A should be chosen.

This basic principle was extended by @bernoulli1954, who suggested that a
persons’ subjective value of money differs depending on their current wealth.
This *diminishing marginal utility* suggests that the more money a person
already has, the less value acquiring more money will have for him. For example,
the experience of a rich man that finds $10 on the street is very different to
the experience of a homeless man that finds $10 [@bradley2013]. Even though $10
was gained in both cases, $10 has less value to a person that already has, for
example, $1000, than for a person that initially only has $10. This principle is
usually modelled as an power function (with a fractional exponent).

<!-- Prospect theory -->

Prospect theory [@kahneman1979; @tversky1992] challenged EUT by suggesting that
people’s subjective value of money does not depend on their state of wealth---it
depends on a change of wealth from a reference point. This is important because
people’s subjective value of money is different depending if they are gaining or
losing money. Specifically, losses have a stronger psychological impact than
equivalent gains. This disparity is one of the most settled and consistent
findings in psychology and economics, having been well-replicated [e.g,
@ruggeri2020]. The fact that losses loom more than equivalent gains for the vast
majority of people is referred to as *loss aversion* [@kahneman1979]. This
finding was the primary reason that Daniel Kahneman won the Nobel Prize in
Economics in 2002 [@kahneman2003]. Loss aversion has been found with small
amounts of money in experimental settings [@kahneman1979; @tversky1992] and with
millions of dollars in corporate settings [@koller2012; @swalm1966]. The effect
has been found in young children [@harbaugh2001], the numerous disparate
cultures in which it has been tested [@weber1998], and even in capuchin monkeys
[@chen2006a]. Furthermore, a neural basis for loss aversion was identified
[@tom2007]. Therefore, loss aversion is clearly central to human cognition and
behaviour.

The function that represents the value of a prospect describes both loss
aversion and diminishing marginal utility, as seen in
Equation \@ref(eq:value-function):
 
\begin{equation}
v(x) = \left\{ \begin{array}{l}
x^\alpha \text{ if } x \ge 0 \\
-\lambda(-x)^\beta \text{ if } x < 0,
(\#eq:value-function)
\end{array} \right.
\end{equation}

where $x$ is the possible outcome, $\lambda$ represents the loss aversion
coefficient, and $\alpha$ and $\beta$ represent the diminishing marginal utility
for gains and losses, respectively.

In other words, loss aversion means that losses have more impact than equivalent
gains. In fact, the impact of loss aversion can be expressed even more
precisely, as a measurement of the ratio of the slopes of the curve for gains
and losses. This measure tells us the average amount that losses have more
impact than equivalent gains. In a sequel to the original prospect theory paper,
@tversky1992 measured a median coefficient ($\lambda$) of 2.25 of loss aversion.
This means that people respond to losses 2.25 times more than equivalent gains.
Similarly, this paper measured a median exponent (representing diminishing
marginal utility, $\alpha$ and $\beta$) of 0.88 for both gains and losses. This
means that people discount money the more of it they have by a rate of
$x^{0.88}$.

Figure \@ref(fig:prospect-theory) shows loss aversion as the function being
steeper in the domain of losses than the domain of gains. It shows diminishing
marginal utility by the slight curve of the function. Equivalent changes in
actual wealth from the references point (x-axis) have different impacts on the
changes’ subjective value (y-axis). An increase in wealth ($x = 1$) brings about
an equivalent increase of value ($y = 1^{0.88} = 1$). However, a decrease in the
same amount of wealth ($x = -1$) brings about a decrease in value 2.25 times the
value of the equivalent gain ($y = -2.25 \cdot (-(-1))^{0.88} = -2.25$).

(ref:prospect-theory) An example of the value function in prospect theory.

```{r prospect-theory, fig.cap = "(ref:prospect-theory)", fig.width = 6, fig.height = 6}
tar_read(prospect_theory)
```

<!-- Management connection -->

This research is relevant to resource allocation because managers often need to
evaluate project proposals that involve an element of risk. Therefore, managers
are likely to be affected by similar effects on risk that have been shown in
laypeople. However, hierarchical organisations offer an even more complex
situation. @lovallo2020 found that the risk profiles of lower-level managers are
lower than those of the top managers. They suggest that this may be due to
lower-level managers' loss aversion to accepting projects that may jeopardise
their job. However, the top managers recognise that a loss in one or more
business units is likely to be offset by gains in other units. Such an
inconsistency in risk profiles across the levels of an hierarchical organisation
fails to take advantage of the benefits of risk aggregation, which has long been
understood in external markets [@markowitz1952]. @lovallo2020 suggested that
lower-level managers’ failure to aggregate risk to the degree desired by top
executives is costing companies approximately a third of the total EV of new
project proposals. It is thus critical to identify ways to support risk
aggregation across organizational hierarchies. The psychological literature
shows that people's risk aggregation is facilitated through various choice
bracketing manipulations. However, there has been no work that investigated such
situations without providing participants with feedback in between decisions;
this critically limits the external validity of this work because in the real
world, organisations evaluate several projects before seeing the outcomes of any
one decision. The experiments presented in Chapter \@ref(aggregation)
investigate the effects of choice bracketing on risk aggregation without
feedback.

### Project similarity

When evaluating project proposals, managers are likely to be influenced by the
relative similarity of the available options to each other. The extent to which
this may be true is important especially since the increase of diversified
firms. Organisations are not only varied by the number of divisions which they
possess, but also by the extent of diversification. This means that managers are
likely to find themselves comparing across dissimilar types of projects.

As mentioned above, there are likely many organisational and financial reasons
why the extent of diversification in an organisation would impact its
performance. However, the impact of psychological factors such as how business
project similarity affects comparing across projects has not been investigated.
This approach is important because the relative similarity of projects has
implications about how difficult the evaluation process becomes and therefore
what kind of financial metrics are used. Having more similar projects to compare
may mean more attributes on which to evaluate, whereas a dissimilar comparison
may lead to a situation in which a manager has to rely on potentially unreliable
metrics.

Structure-mapping theory [SMT\; @gentner1997; @gentner1983] provides a model of
comparison that psychologically distinguishes similar and dissimilar allocation
tasks. SMT models comparison as a process of bringing conceptual structures into
alignment which, when possible, puts shared dimensions into correspondence.
Alignment both highlights when two conceptual structures share dimensions, but
also highlights how the two structures differ along those shared dimensions,
called *alignable differences*. For example, when comparing two oil discovery
projects, all the relevant processes of planning an exploration and measuring
the amount of hydrocarbons in a prospect might be identical, but the specific
amount measured will be different. This is the alignable difference: a
difference between the two projects that is constrained within the same
conceptual structure. However, when comparing between an oil field and a
refinery, there will be significantly more *non-alignable differences*, because
the two domains do not share component dimensions. That is, many of the
processes that exist in the exploration business unit have a significantly
different dimensional structure to those in the refinery business unit, such
that it will be difficult to find meaningful alignments. More non-alignable
differences mean that there are less opportunities to make meaningful
comparisons, and so would make predicting relative project success and ranking
their priority more difficult. Chapter \@ref(alignment) experimentally examines
business project comparisons and how project alignment affects resource
allocation decisions.

<!-- Metric variance -->

When evaluating projects, managers make use of financial metrics, such as NPV.
However, such metrics are reliant on forecast estimates of, for instance, future
cash flows. Do managers take into account such inherent variance in their
decisions? This is especially important to investigate given the above
discussion. In cases of non-alignable comparison managers might be relying on a
potentially unreliable metric. On the other hand, in an alignable comparison,
managers might have the option to moderate their choice based on the relative
reliability of different metrics. It is important to remember that all such
decisions are often very consequential for the manager. That is, the project
could ultimately make the company money and lead to future opportunities for the
manager, or potentially cause financial harm to the company (and subsequently
lead to a job loss).

Psychological research shows that laypeople are in general quite poor at using
numerical variance information [@galesic2010; @konold1993; @vivalt2021;
@batteux2020]. However, it is unclear to what extent managers would be sensitive
to variance information in the metrics associated with the projects that they
evaluate. On the one hand, perhaps managers' financial training will allow a
consideration of such variance estimates, but this might not manifest in a
situation in which managers have already been shown to be prone to biases.
Chapter \@ref(alignment) investigates whether people are as sensitive to
verbally-instructed reliability information as they are to numerical reliability
information.

### Reasoning from past cases

Managers often use past events to reason and make predictions about the future
[@einhorn1987]. Such past events may be those that happened to the individual
manager, a case from the organisation's history, or from an external source.
This will especially be the case in a project evaluation scenario when a given
project is hard to compare with the other projects at hand. However, managers
evaluating project proposals may make inappropriate comparisons when considering
the target project to other cases. For instance, people tend to limit the sample
size of the set of comparison cases to a target problem to a small number. Often
only a handful of cases, or even one. Doing this might mean only considering
potentially irrelevant surface similarity to the current situation and not an
alignment of the underlying causal structure. Further, this might mean not
considering other similar projects.

@tversky1974 discussed a number of biases that may influence such processes. The
availability bias is seen when people mistake the ease of retrieval of
information for its frequency. Further, research on analogical retrieval showed
that people are more likely to retrieve surface similar cases than those with a
relational connection [@gentner1993]. As such, managers are likely to recall
cases that may not be sufficiently relevant to their target situation and be
overly-confident about the frequency of such cases occurring. Such a focus on a
particular case might then also lead to an anchoring effect, wherein other
decisions might be disproportionately seen as relevant. @tversky1974 also found
that people are not sensitive to properties of sample size such as the greater
amount of non-representative outcomes in small samples. This means that managers
are even less likely to appreciate the importance of considering a large sample
of cases when drawing conclusions to a target problem. @tversky1974 also note an
insensitivity to predictability, in which people do not take into account the
reliability of the information that they have to make a prediction. This might
mean that managers may struggle to ideally weigh evidence of varying degrees of
reliability.

External sources that might be used to compare to a target situation include
business case studies. Considering such examples of prior business decisions or
events are the way that most MBAs learn about the business world. Publications
such as Forbes or Harvard Business Review publicise various businesses'
successes and failures and so may create an allure to use such case studies in
the decision-making process. On the other hand, managers may have access to more
aggregated data about their industry from, for instance, consultancy companies.
How do managers use these various types of evidence in their decision-making?

Research on this topic suggests that managers tend to prefer anecdotes over
statistics, unless aided [@wainberg2018]. This is a concern because @gavetti2005
suggests that managers often make use of case studies quite poorly. The analogy
literature draws a distinction between surface similarity, in which a mapping is
made between easily identifiable but potentially functionally irrelevant
attributes, and relational similarity, in which the underlying mechanism is
considered. Are managers sensitive to the deeper causal mechanisms that underlie
the anecdotes they judge? Or are they simply influenced by surface similarity?
Chapter \@ref(anecdotes) investigates the extent to which people moderate their
reliance on anecdotes or aggregated data by the relevance of the anecdote to the
target project during resource allocation. It also considers whether people are
sensitive to information about the distribution from which the anecdote was
sampled.

